import google.generativeai as genai
import os
import streamlit as st
from PIL import Image
import requests
from io import BytesIO
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials
import matplotlib.pyplot as plt

genai.configure(api_key="AIzaSyAR8fzlgtlQbc8I80Cf6XcqBtFg4EJ-pPA")
model = genai.GenerativeModel("gemini-1.5-flash") #this is the free model of google gemini


# Title Page
st.markdown("## 💕 Welcome to the Playlit Generator💽")
st.markdown("Enter your mood, favorite genre, or artist and we’ll generate a personalized playlist just for you using live Spotify data! 🎀")

# 🔑 Spotify Credentials 
CLIENT_ID = "ebacc0035f8647088fd24e64db4ccd01"
CLIENT_SECRET = "b3c67ed940414fef919d08cef920e3df"


# Authenticate with Spotify
auth_manager = SpotifyClientCredentials(client_id=CLIENT_ID, client_secret=CLIENT_SECRET)
sp = spotipy.Spotify(auth_manager=auth_manager)


def organizedTracks(searchT, limit=10):
    results=sp.search(q=searchT, type="track", limit=limit)
    tracks=results['tracks']['items']

    organized_data=[]

    for track in tracks:
        tracks_ids=track['id']
    
    for i, track in enumerate(tracks):
        artistID=track['artists'][0]['id']
        artist=sp.artist(artistID)
        trackInfo={
            "song_name":track["name"],
            "artist":track['artists'][0]['name'],
            "album":track['album']['name'],
            "relDate": track['album']['release_date'],
            'popularity':track['popularity'],
            'url':track['external_urls']['spotify'],
            'genre': artist['genres'],
            }
        organized_data.append(trackInfo)
    return organized_data

def buildPrompt(artist, genre):
    return f"Suggest 5 to 7 songs in th e{genre} genre for someone who's favorite artist is {artist}. List the songs in the format Song - Artist. Finally, write a short description of the playlist vibe."

st.title ("🎶 Playlist Generator")
artist_input= st.text_input("Enter a favorite artist")
genre_input= st.selectbox("Pick a genre", ["Pop", "Hip-Hop", "Rock", "R&B", "Jazz", "EDM", "Electronic", "Reggaeton", "Indie", "Country"])

if st.button("Generate Playlist"):
    if not artist_input:
        st.warning("Please enter artist")
    else: 
        with st.spinner("Asking Gemini for recommendations..."):
            prompt=buildPrompt(artist_input, genre_input.lower())
            response = model.generate_content(prompt)
            finalText=response.text.strip()
        
        lines= finalText.split ("\n")
        songs=[]
        description=[]

        for line in lines:
            if " - " in line:
                parts=line.split(" - ")
                if len(parts)==2:
                    song_name, sartist=parts
                    songs.append(f"{song_name.strip()} {sartist.strip()}")
            elif line.strip():
                description.append(line.strip())
        finalPlaylist=[]
        for searchT in songs:
            track_results=organizedTracks(searchT,limit=1)
            if track_results:
                finalPlaylist.append(track_results[0])
        
        st.subheader("✨ Playlist Vibe generated by Gemini")
        for t in description:
            st.write (t)
        

        st.subheader("📋 Your Playlist")
        for track in finalPlaylist:
            st.markdown(f"**{track['song_name']}**")
            st.markdown(f"**🕺 Artist:** {track['artist']}")
            st.markdown(f"**📻 Album:** {track['album']}")
            st.markdown(f"**🗓️ Release Date:** {track['relDate']}")
            st.markdown(f"[Listen on Spotify]({track['url']})")
            st.markdown("---")

        